# docker-compose.yml - #TODO update to use Ansible configuration - currently based on Web Dev Cookbook template
# Using Compose File reference version 2.2 due to docker version installed
version: '2' # version of docker-config standard not the file version

services:
  db:
    image: postgres:12.1
    environment:
      - POSTGRES_DB=pg-docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db_network
  djangoapp:
    build: .
    depends_on:
      - db
    volumes:
#      - ./arcsApp
      - ./arcsApp:/var/www/arcsApp/
    ports:
      - 8000:8000
    command:
      python3 manage.py runserver 127.0.0.1:8000

  nginximg:
    image: nginx:latest
    depends_on:
      - djangoapp
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf' #copy local nginx.conf file from /opt directory relative to execution
    networks:
      - nginx_network
networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
#  databas
#      - '/var/run/docker.sock:/tmp/docker.sock:ro'
#      - './config/my.cnf:/etc/mysql/conf.d/my.cnf'
#      - './mysql:/var/lib/mysql'
#      - './data:/usr/local/share/data'
#    environment:
#      - 'MYSQL_ROOT_PASSWORD'
#      - 'MYSQL_USER'
#      - 'MYSQL_PASSWORD'
#      - 'MYSQL_DATABASE'
#      ArcsCore:
#        build: .
#        command:
#          python3 manage.py runserver 0.0.0.0:8000
#          volumes:
#            - './ARCSystem:/usr/src/app/ARCSystem'
#        - './media:/usr/src/app/media'
#        - './static:/usr/src/app/static'
#        - './templates:/usr/src/app/templates'
#        - './apps/external:/usr/src/app/external'
#        - './apps/myapp1:/usr/src/app/myapp1'
#        - './apps/myapp2:/usr/src/app/myapp2'
#          ports:
#            - '8000'
#      links:
#         - db
#      environment:
#         - 'SITE_HOST'
#         - 'MEDIA_HOST'
#         - 'STATIC_HOST'
#         - 'VIRTUAL_HOST=${SITE_HOST}'
#         - 'VIRTUAL_PORT=8000'
#         - 'MYSQL_HOST=db'
#         - 'MYSQL_USER'
#         - 'MYSQL_PASSWORD'
#         - 'MYSQL_DATABASE'
#      media:

#image: 'httpd:latest' volumes:
#  - './media:/usr/local/apache2/htdocs'
#  ports: - '80' environment:
#    - 'VIRTUAL_HOST=${MEDIA_HOST}'
#    static:
#      image:
#        'httpd:latest'
#      volumes:
#        - './static:/usr/local/apache2/htdocs'
#        ports:
#          environment:
#            - 'VIRTUAL_HOST=${STATIC_HOST}'
#            - '80'
